version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mindplate_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mindplate
      MYSQL_USER: mindplate
      MYSQL_PASSWORD: mindplate
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build: .
    container_name: mindplate_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8025:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000


volumes:
  mysql_data:
