version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mindplate_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mindplate
    volumes:
      - mindplate_data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build: .
    container_name: mindplate_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "sleep 10 &&
             uvicorn main:app --host 0.0.0.0 --port 8000"

volumes:
  mindplate_data:
